### ISSUE TITLE
[0.5pt] Setup Kanban

### ISSUE THREAD

**Issue by AlphaNtihinduka** [AlphaNtihinduka/food_reciepe#2]
## Kanban Board
 - [Repository Link](https://github.com/AlphaNtihinduka/food_reciepe)
 - [Project Kanban board Link](https://github.com/AlphaNtihinduka/food_reciepe/projects/1)
 
 ### Authors:
- Rodrigo Johann Reckziegel Nunes https://github.com/AlphaNtihinduka/food_reciepe/issues/6
- Aron Abraham https://github.com/AlphaNtihinduka/food_reciepe/issues/3
- Ntihinduka Alpha https://github.com/AlphaNtihinduka/food_reciepe/issues/8

**Comment by uwadonat** [comment]
## Hi @Team!

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Very descriptive and clean pull request message ✔️

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
